apiVersion: v1
kind: Service
metadata:
  name: cloudsql-desa-admin-proxy-service
  namespace: tax-innovation-qa
spec:
  ports:
    - name: cloudsql-desa-admin-proxy-service
      port: 5432
  selector:
    unit: desaadmincloudsql
