# Generated by Django 3.1.1 on 2021-03-08 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text=('Indica si el registro debe ser tratado como activo.', 'Desmarque esta opción en lugar de borrar el registro'), verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Ultima modificación')),
                ('issuer_rfc', models.CharField(blank=True, help_text='rfc issuer', max_length=20, null=True, verbose_name='issuer_rfc')),
                ('issuer_name', models.CharField(blank=True, help_text='name issuer', max_length=300, null=True, verbose_name='issuer_name')),
                ('payer_rfc', models.CharField(blank=True, help_text='rfc payer', max_length=20, null=True, verbose_name='payer_rfc')),
                ('payer_name', models.CharField(blank=True, help_text='name payer', max_length=300, null=True, verbose_name='payer_name')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listo_api_informacion_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listo_api_informacion_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
            ],
            options={
                'verbose_name': 'Informacion',
                'verbose_name_plural': 'Infomracion de usuarios',
            },
        ),
    ]
