# Generated by Django 3.1.1 on 2021-03-08 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listo_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='users_user',
            field=models.ForeignKey(default=51, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Usuario User'),
            preserve_default=False,
        ),
    ]
