# Generated by Django 3.1.1 on 2021-03-10 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listo_api', '0002_informacion_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionLegal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text=('Indica si el registro debe ser tratado como activo.', 'Desmarque esta opción en lugar de borrar el registro'), verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Ultima modificación')),
                ('act_eco', models.CharField(blank=True, help_text='actividades economicas', max_length=300, null=True, verbose_name='act_eco')),
                ('estatus_domicilio', models.CharField(blank=True, help_text='estatus domicilio', max_length=100, null=True, verbose_name='estatus_domicilio')),
                ('estatus_cont_dom', models.CharField(blank=True, help_text='estatus contribuyente domicilio', max_length=200, null=True, verbose_name='estatus_cont_dom')),
                ('fecha_alta_dom', models.CharField(blank=True, help_text='fecha alta domicilio', max_length=60, null=True, verbose_name='fecha_alta_dom')),
                ('ad', models.CharField(blank=True, help_text='ad', max_length=100, null=True, verbose_name='ad')),
                ('nomb_ent_fed', models.CharField(blank=True, help_text='nombre entidad federativa', max_length=100, null=True, verbose_name='nomb_ent_fed')),
                ('nomb_muni_demar_terri', models.CharField(blank=True, help_text='nombre entidad federativa', max_length=100, null=True, verbose_name='nomb_ent_fed')),
                ('nombre_localidad', models.CharField(blank=True, help_text='nombre localidad', max_length=100, null=True, verbose_name='nombre_localidad')),
                ('nombre_colonia', models.CharField(blank=True, help_text='nombre colonia', max_length=100, null=True, verbose_name='nombre_colonia')),
                ('nombre_vialidad', models.CharField(blank=True, help_text='nombre vialidad', max_length=100, null=True, verbose_name='nombre_vialidad')),
                ('numero_exterior', models.CharField(blank=True, help_text='numero exterior', max_length=100, null=True, verbose_name='numero_exterior')),
                ('numero_interior', models.CharField(blank=True, help_text='numero interior', max_length=100, null=True, verbose_name='numero_interior')),
                ('entre_calle', models.CharField(blank=True, help_text='entre calle', max_length=100, null=True, verbose_name='entre_calle')),
                ('y_calle', models.CharField(blank=True, help_text='y calle', max_length=100, null=True, verbose_name='y_calle')),
                ('tipo_vialidad', models.CharField(blank=True, help_text='tipo vialidad', max_length=100, null=True, verbose_name='tipo_vialidad')),
                ('cod_pos', models.CharField(blank=True, help_text='codigo postal', max_length=20, null=True, verbose_name='cod_pos')),
                ('tipo_inmueble', models.CharField(blank=True, help_text='tipo inmueble', max_length=100, null=True, verbose_name='tipo_inmueble')),
                ('tel_fijo', models.CharField(blank=True, help_text='telefono fijo', max_length=20, null=True, verbose_name='tel_fijo')),
                ('tel_movil', models.CharField(blank=True, help_text='telefono movil', max_length=20, null=True, verbose_name='tel_movil')),
                ('correo', models.CharField(blank=True, help_text='correo', max_length=50, null=True, verbose_name='correo')),
                ('referencia', models.CharField(blank=True, help_text='referencia', max_length=150, null=True, verbose_name='referencia')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listo_api_direccionlegal_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listo_api_direccionlegal_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
                ('users_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Direccion User')),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direccion legal',
            },
        ),
    ]
