# Generated by Django 3.1.1 on 2021-03-10 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listo_api', '0003_direccionlegal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista69',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text=('Indica si el registro debe ser tratado como activo.', 'Desmarque esta opción en lugar de borrar el registro'), verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Ultima modificación')),
                ('counterparty_rfc', models.CharField(blank=True, help_text='counterparty rfc', max_length=25, null=True, verbose_name='counterparty_rfc')),
                ('rfc_name', models.CharField(blank=True, help_text='rfc name', max_length=100, null=True, verbose_name='rfc_name')),
                ('state', models.CharField(blank=True, help_text='state', max_length=80, null=True, verbose_name='state')),
                ('list_type', models.CharField(blank=True, help_text='list type', max_length=80, null=True, verbose_name='list_type')),
                ('status', models.CharField(blank=True, help_text='status', max_length=50, null=True, verbose_name='status')),
                ('entry_date', models.CharField(blank=True, help_text='entry date', max_length=20, null=True, verbose_name='entry_date')),
                ('folio', models.CharField(blank=True, help_text='folio', max_length=100, null=True, verbose_name='folio')),
                ('customer_name', models.CharField(blank=True, help_text='customer name', max_length=100, null=True, verbose_name='customer_name')),
                ('customer_rfc', models.CharField(blank=True, help_text='name payer', max_length=25, null=True, verbose_name='payer_name')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listo_api_lista69_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listo_api_lista69_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
                ('users_lista69b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Lista 69b')),
            ],
            options={
                'verbose_name': 'Informacion',
                'verbose_name_plural': 'Infomracion de usuarios',
            },
        ),
    ]
