# Generated by Django 3.1.1 on 2021-03-11 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listo_api', '0005_auto_20210310_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracionesDiots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text=('Indica si el registro debe ser tratado como activo.', 'Desmarque esta opción en lugar de borrar el registro'), verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Ultima modificación')),
                ('id_dec', models.CharField(blank=True, help_text='id de declaraciones', max_length=30, null=True, verbose_name='id_dec')),
                ('period_type', models.CharField(blank=True, help_text='period type', max_length=50, null=True, verbose_name='period_type')),
                ('period', models.CharField(blank=True, help_text='period', max_length=20, null=True, verbose_name='period')),
                ('year', models.IntegerField(blank=True, help_text='year', null=True, verbose_name='year')),
                ('total_paid_due', models.CharField(blank=True, help_text='total paid due', max_length=30, null=True, verbose_name='total_paid_due')),
                ('filing_due_on', models.CharField(blank=True, help_text='filing due on', max_length=30, null=True, verbose_name='filing_due_on')),
                ('diot_due_on', models.CharField(blank=True, help_text='diot due on', max_length=20, null=True, verbose_name='diot_due_on')),
                ('payment_status', models.CharField(blank=True, help_text='payment status', max_length=100, null=True, verbose_name='payment_status')),
                ('period_description', models.CharField(blank=True, help_text='period description', max_length=20, null=True, verbose_name='period_description')),
                ('period_type_description', models.CharField(blank=True, help_text='period type description', max_length=30, null=True, verbose_name='period_type_description')),
                ('general_status', models.CharField(blank=True, help_text='general status', max_length=100, null=True, verbose_name='general_status')),
                ('diot_general_status', models.CharField(blank=True, help_text='numero exterior', max_length=100, null=True, verbose_name='numero_exterior')),
                ('days_to_pay', models.CharField(blank=True, help_text='days to pay', max_length=30, null=True, verbose_name='days_to_pay')),
                ('days_to_file', models.CharField(blank=True, help_text='days to file', max_length=30, null=True, verbose_name='days_to_file')),
                ('to_be_paid_due', models.CharField(blank=True, help_text='to be paid due', max_length=30, null=True, verbose_name='to_be_paid_due')),
                ('compensable_due', models.CharField(blank=True, help_text='compensable due', max_length=30, null=True, verbose_name='compensable_due')),
                ('payable_due', models.CharField(blank=True, help_text='payable due', max_length=20, null=True, verbose_name='payable_due')),
                ('checksum', models.CharField(blank=True, help_text='checksum', max_length=30, null=True, verbose_name='checksum')),
                ('nearest_payment_on', models.CharField(blank=True, help_text='nearest payment on', max_length=100, null=True, verbose_name='nearest_payment_on')),
                ('last_payment_on', models.CharField(blank=True, help_text='last payment on', max_length=30, null=True, verbose_name='last_payment_on')),
                ('last_filing_filed_on', models.CharField(blank=True, help_text='last filing filed on', max_length=30, null=True, verbose_name='last_filing_filed_on')),
                ('days_to_file_diot', models.CharField(blank=True, help_text='days to file diot', max_length=20, null=True, verbose_name='days_to_file_diot')),
                ('last_diot_filed_on', models.CharField(blank=True, help_text='last_diot_filed_on', max_length=30, null=True, verbose_name='last_diot_filed_on')),
                ('expired_taxes', models.CharField(blank=True, help_text='expired taxes', max_length=30, null=True, verbose_name='expired_taxes')),
                ('has_unkown_payment_status', models.CharField(blank=True, help_text='has unkown payment status', max_length=30, null=True, verbose_name='has_unkown_payment_status')),
                ('period_only_description', models.CharField(blank=True, help_text='period only description', max_length=30, null=True, verbose_name='period_only_description')),
                ('period_short_description', models.CharField(blank=True, help_text='period short description', max_length=30, null=True, verbose_name='period_short_description')),
                ('creditable_due', models.CharField(blank=True, help_text='creditable due', max_length=20, null=True, verbose_name='creditable_due')),
                ('taxes', models.CharField(blank=True, help_text='taxes', max_length=40, null=True, verbose_name='taxes')),
                ('capture_line_expire_on', models.CharField(blank=True, help_text='capture line expire on', max_length=60, null=True, verbose_name='capture_line_expire_on')),
                ('has_complementary_filings', models.CharField(blank=True, help_text='has complementary filings', max_length=60, null=True, verbose_name='has_complementary_filings')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listo_api_declaracionesdiots_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listo_api_declaracionesdiots_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
                ('users_diots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Diots User')),
            ],
            options={
                'verbose_name': 'Estatus DeclaracionesDiots',
                'verbose_name_plural': 'Estatus DeclaracionesDiots',
            },
        ),
    ]
