# Generated by Django 3.1.1 on 2021-03-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listo_api', '0006_declaracionesdiots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracionesdiots',
            name='taxes',
            field=models.CharField(blank=True, help_text='taxes', max_length=350, null=True, verbose_name='taxes'),
        ),
    ]
