# Generated by Django 3.1.1 on 2021-04-14 21:23

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listo_api', '0007_auto_20210311_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='is_income',
            field=models.CharField(blank=True, help_text='is income', max_length=20, null=True, verbose_name='is_income'),
        ),
        migrations.AddField(
            model_name='informacion',
            name='json_invoice',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
