# Generated by Django 3.1.1 on 2021-04-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listo_api', '0008_auto_20210414_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='is_payroll',
            field=models.BooleanField(default=False, help_text='Indicates if the invoice is payroll.', verbose_name='is payroll'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='is_income',
            field=models.BooleanField(default=False, help_text='Indicates if the invoice is income.', verbose_name='is income'),
        ),
    ]
