# Generated by Django 3.1.1 on 2021-04-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listo_api', '0009_auto_20210414_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='total',
            field=models.CharField(blank=True, help_text='total', max_length=300, null=True, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='payer_rfc',
            field=models.CharField(blank=True, help_text='rfc payer', max_length=100, null=True, verbose_name='payer_rfc'),
        ),
    ]
