# Generated by Django 3.1.1 on 2021-04-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listo_api', '0010_auto_20210414_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='canceled_on',
            field=models.CharField(blank=True, help_text='canceled on', max_length=300, null=True, verbose_name='canceled_on'),
        ),
    ]
