# Generated by Django 3.1.1 on 2021-04-22 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listo_api', '0012_opinioncumplimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDeclaracionesDiots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text=('Indica si el registro debe ser tratado como activo.', 'Desmarque esta opción en lugar de borrar el registro'), verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Ultima modificación')),
                ('detalle_declaracion_id', models.CharField(blank=True, help_text='id de declaracion', max_length=300, null=True, verbose_name='id_detalle_declaraciones')),
                ('operation_number', models.CharField(blank=True, help_text='numero de operación de la declaración', max_length=300, null=True, verbose_name='operation_numbers')),
                ('rfc', models.CharField(blank=True, help_text='RFC', max_length=300, null=True, verbose_name='rfc')),
                ('filed_timestamp', models.CharField(blank=True, help_text=' hora de captura', max_length=300, null=True, verbose_name='filed_timestamp')),
                ('filing_type', models.CharField(blank=True, help_text='tipo de la declaración', max_length=300, null=True, verbose_name='filing_type')),
                ('complimentary_type', models.CharField(blank=True, help_text='tipo de la declaración complementaria', max_length=300, null=True, verbose_name='complimentary_type')),
                ('filed_on', models.CharField(blank=True, help_text='fecha de la presentacion de la declaración', max_length=300, null=True, verbose_name='filed_on')),
                ('capture_line_expire_on', models.CharField(blank=True, help_text='fecha y hora en la que expira', max_length=300, null=True, verbose_name='operation_numbers')),
                ('unknown_payment_status', models.CharField(blank=True, help_text='numero de operación de la declaración', max_length=300, null=True, verbose_name='unknown_payment_status')),
                ('capture_line', models.CharField(blank=True, help_text='línea de captura de la declaración', max_length=300, null=True, verbose_name='capture_line')),
                ('total_due', models.CharField(blank=True, help_text='monto por pagar Pesos', max_length=300, null=True, verbose_name='total_due')),
                ('total_paid_due', models.CharField(blank=True, help_text=' monto pagado pesos', max_length=300, null=True, verbose_name='total_paid_due')),
                ('is_paid', models.CharField(blank=True, help_text='si la declaración fue pagada', max_length=300, null=True, verbose_name='is_paid')),
                ('bank', models.CharField(blank=True, help_text='nombre del banco en el que fue efectuado el pago', max_length=300, null=True, verbose_name='bank')),
                ('paid_on', models.CharField(blank=True, help_text='fecha en la que fue efectuado el pago', max_length=300, null=True, verbose_name='operation_numbers')),
                ('payment_operation', models.CharField(blank=True, help_text='número de la operación bancaria', max_length=300, null=True, verbose_name='operation_numbers')),
                ('filed_filing_file', models.CharField(blank=True, help_text='id del archivo con Hoja de Trabajo', max_length=300, null=True, verbose_name='filed_filing_file')),
                ('receipt_filing_file', models.CharField(blank=True, help_text='id del archivo con Acuse del Recibo', max_length=300, null=True, verbose_name='receipt_filing_file')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listo_api_detalledeclaracionesdiots_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listo_api_detalledeclaracionesdiots_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
            ],
            options={
                'verbose_name': 'DetalleDeclaracionesDiot',
                'verbose_name_plural': 'DetalleDeclaracionesDiots',
            },
        ),
    ]
