# Generated by Django 3.1.1 on 2021-04-23 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listo_api', '0013_detalledeclaracionesdiots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaracionesdiots',
            name='id_dec',
        ),
        migrations.RemoveField(
            model_name='declaracionesdiots',
            name='users_diots',
        ),
        migrations.AddField(
            model_name='declaracionesdiots',
            name='filing_period_id',
            field=models.CharField(blank=True, help_text='id de periodo', max_length=30, null=True, verbose_name='filing_period_id'),
        ),
        migrations.AddField(
            model_name='declaracionesdiots',
            name='users_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User related'),
        ),
        migrations.CreateModel(
            name='Declaraciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text=('Indica si el registro debe ser tratado como activo.', 'Desmarque esta opción en lugar de borrar el registro'), verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Ultima modificación')),
                ('rfc', models.CharField(blank=True, help_text='rfc de la declaracion', max_length=300, null=True, verbose_name='rfc_filing')),
                ('filing_period', models.CharField(blank=True, help_text='id del periodo de la declaración', max_length=300, null=True, verbose_name='filing_period')),
                ('filing_id', models.CharField(blank=True, help_text='id de la declaracion', max_length=300, null=True, verbose_name='filing_id')),
                ('filed_timestamp', models.CharField(blank=True, help_text='hora de captura formato', max_length=300, null=True, verbose_name='filed_timestamp')),
                ('operation_number', models.CharField(blank=True, help_text='número de operación de la declaración', max_length=300, null=True, verbose_name='operation_number')),
                ('filing_type', models.CharField(blank=True, help_text='tipo de la declaración', max_length=300, null=True, verbose_name='filing_type')),
                ('filed_on', models.CharField(blank=True, help_text='fecha de la presentacion de la declaración', max_length=300, null=True, verbose_name='filed_on')),
                ('capture_line_expire_on', models.CharField(blank=True, help_text='fecha y hora en la que expira la línea de captura', max_length=300, null=True, verbose_name='capture_line_expire_on')),
                ('days_to_pay', models.CharField(blank=True, help_text='cantidad de días restantes para pagar la declaración', max_length=300, null=True, verbose_name='days_to_pay')),
                ('general_status', models.CharField(blank=True, help_text='estatus general de la declaración', max_length=300, null=True, verbose_name='general_status')),
                ('payment_status', models.CharField(blank=True, help_text='código del estatus de pago', max_length=300, null=True, verbose_name='payment_status')),
                ('unknown_payment_status', models.CharField(blank=True, help_text='si SAT no tiene información sobre el pago', max_length=300, null=True, verbose_name='unknown_payment_status')),
                ('expired_taxes', models.CharField(blank=True, help_text='id de la declaracion', max_length=300, null=True, verbose_name='expired_taxes')),
                ('capture_line', models.CharField(blank=True, help_text='línea de captura de la declaración', max_length=300, null=True, verbose_name='capture_line')),
                ('total_due', models.CharField(blank=True, help_text='monto por apgar', max_length=300, null=True, verbose_name='total_due')),
                ('total_paid_due', models.CharField(blank=True, help_text='monto pagado', max_length=300, null=True, verbose_name='filing_id')),
                ('creditable_due', models.CharField(blank=True, help_text='summa de saldos a favor acreditables', max_length=300, null=True, verbose_name='creditable_due')),
                ('compensable_due', models.CharField(blank=True, help_text='summa de de saldos a favor compensables', max_length=300, null=True, verbose_name='compensable_due')),
                ('checksum', models.CharField(blank=True, help_text='Suma de verificación', max_length=300, null=True, verbose_name='checksum')),
                ('is_paid', models.CharField(blank=True, help_text='si la declaración fue pagada', max_length=300, null=True, verbose_name='is_paid')),
                ('bank', models.CharField(blank=True, help_text='nombre del banco con el que fue efectuado el pago', max_length=300, null=True, verbose_name='bank')),
                ('paid_on', models.CharField(blank=True, help_text='fecha en la que fue efectuado el pago', max_length=300, null=True, verbose_name='paid_on')),
                ('payment_operation', models.CharField(blank=True, help_text='id de la declaracion', max_length=300, null=True, verbose_name='payment_operation')),
                ('filed_filing_file', models.CharField(blank=True, help_text='id del archivo con Hoja de Trabajo', max_length=300, null=True, verbose_name='filed_filing_file')),
                ('receipt_filing_file', models.CharField(blank=True, help_text='id del archivo con Acuse del Recibo', max_length=300, null=True, verbose_name='receipt_filing_file')),
                ('paid_filing_file', models.CharField(blank=True, help_text='id del archivo con Acuse de Pago', max_length=300, null=True, verbose_name='paid_filing_file')),
                ('payment_filing_file', models.CharField(blank=True, help_text='id del archivo con Acuse del Recibo', max_length=300, null=True, verbose_name='payment_filing_file')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listo_api_declaraciones_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listo_api_declaraciones_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
                ('user_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User related')),
            ],
            options={
                'verbose_name': 'Declaraciones',
                'verbose_name_plural': 'Declaraciones',
            },
        ),
    ]
