# Generated by Django 3.1.1 on 2021-04-23 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listo_api', '0014_auto_20210422_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaraciones',
            old_name='user_related',
            new_name='users_declaraciones',
        ),
        migrations.RenameField(
            model_name='declaracionesdiots',
            old_name='users_related',
            new_name='users_declaracionesdiots',
        ),
    ]
