# Generated by Django 3.1.1 on 2021-04-23 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listo_api', '0015_auto_20210422_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text=('Indica si el registro debe ser tratado como activo.', 'Desmarque esta opción en lugar de borrar el registro'), verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Ultima modificación')),
                ('diot_id', models.CharField(blank=True, help_text='Id del Diot', max_length=300, null=True, verbose_name='diot_id')),
                ('rfc', models.CharField(blank=True, help_text='rfc', max_length=300, null=True, verbose_name='rfc')),
                ('model_version', models.CharField(blank=True, max_length=300, null=True, verbose_name='model_version')),
                ('folder', models.CharField(blank=True, help_text='folder', max_length=300, null=True, verbose_name='folder')),
                ('diot_type', models.CharField(blank=True, help_text='diot_type', max_length=300, null=True, verbose_name='diot_type')),
                ('filed_on', models.CharField(blank=True, help_text='filed_on', max_length=300, null=True, verbose_name='filed_on')),
                ('accountant', models.CharField(blank=True, help_text='accountant', max_length=300, null=True, verbose_name='accountant')),
                ('receipt', models.CharField(blank=True, help_text='receipt', max_length=300, null=True, verbose_name='receipt')),
                ('filing_period', models.CharField(blank=True, help_text='filing_period', max_length=300, null=True, verbose_name='filing_period')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listo_api_diots_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listo_api_diots_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
                ('users_diots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User related')),
            ],
            options={
                'verbose_name': 'Diot',
                'verbose_name_plural': 'Diots',
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text=('Indica si el registro debe ser tratado como activo.', 'Desmarque esta opción en lugar de borrar el registro'), verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Ultima modificación')),
                ('issuer_rfc', models.CharField(blank=True, help_text='rfc issuer', max_length=20, null=True, verbose_name='issuer_rfc')),
                ('issuer_name', models.CharField(blank=True, help_text='name issuer', max_length=300, null=True, verbose_name='issuer_name')),
                ('payer_rfc', models.CharField(blank=True, help_text='rfc payer', max_length=100, null=True, verbose_name='payer_rfc')),
                ('is_income', models.BooleanField(default=False, help_text='Indicates if the invoice is income.', verbose_name='is income')),
                ('is_payroll', models.BooleanField(default=False, help_text='Indicates if the invoice is payroll.', verbose_name='is payroll')),
                ('payer_name', models.CharField(blank=True, help_text='name payer', max_length=300, null=True, verbose_name='payer_name')),
                ('canceled_on', models.CharField(blank=True, help_text='canceled on', max_length=300, null=True, verbose_name='canceled_on')),
                ('total', models.CharField(blank=True, help_text='total', max_length=300, null=True, verbose_name='total')),
                ('json_invoice', jsonfield.fields.JSONField(default=dict)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listo_api_facturas_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listo_api_facturas_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
                ('users_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario User')),
            ],
            options={
                'verbose_name': 'Informacion',
                'verbose_name_plural': 'Infomracion de usuarios',
            },
        ),
        migrations.RenameField(
            model_name='opinioncumplimiento',
            old_name='users_opinion_cumplimiento',
            new_name='users_opinioncumplimiento',
        ),
        migrations.DeleteModel(
            name='Informacion',
        ),
    ]
