# Generated by Django 3.1.1 on 2021-04-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listo_api', '0017_auto_20210423_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='bank',
            field=models.CharField(blank=True, help_text='bank', max_length=500, null=True, verbose_name='bank'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='capture_line',
            field=models.CharField(blank=True, help_text='capture_line', max_length=500, null=True, verbose_name='capture_line'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='capture_line_expire_on',
            field=models.CharField(blank=True, help_text='capture_line_expire_on', max_length=500, null=True, verbose_name='capture_line_expire_on'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='complimentary_type',
            field=models.CharField(blank=True, help_text='complimentary_type', max_length=500, null=True, verbose_name='complimentary_type'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='credit_balance_originations',
            field=models.CharField(blank=True, help_text='credit_balance_originations', max_length=500, null=True, verbose_name='credit_balance_originations'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='credit_balance_reductions',
            field=models.CharField(blank=True, help_text='credit_balance_reductions', max_length=500, null=True, verbose_name='credit_balance_reductions'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='declaracion_detalle_id',
            field=models.CharField(blank=True, help_text='declaracion detalle id', max_length=500, null=True, verbose_name='declaracion_detalle_id'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='filed_filing_file',
            field=models.CharField(blank=True, help_text='filed_filing_file', max_length=500, null=True, verbose_name='filed_filing_file'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='filed_on',
            field=models.CharField(blank=True, help_text='filed_on', max_length=500, null=True, verbose_name='filed_on'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='filed_timestamp',
            field=models.CharField(blank=True, help_text='filed_timestamp', max_length=500, null=True, verbose_name='filed_timestamp'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='filing_period',
            field=models.CharField(blank=True, help_text='filing_period', max_length=500, null=True, verbose_name='filing_period'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='filing_type',
            field=models.CharField(blank=True, help_text='filing_type', max_length=500, null=True, verbose_name='filing_type'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='financial_statement',
            field=models.CharField(blank=True, help_text='financial_statement', max_length=500, null=True, verbose_name='financial_statement'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='is_paid',
            field=models.CharField(blank=True, help_text='is_paid', max_length=500, null=True, verbose_name='is_paid'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='operation_number',
            field=models.CharField(blank=True, help_text='name payer', max_length=500, null=True, verbose_name='operation_number'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='paid_filing_file',
            field=models.CharField(blank=True, help_text='paid_filing_file', max_length=500, null=True, verbose_name='paid_filing_file'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='paid_on',
            field=models.CharField(blank=True, help_text='paid_on', max_length=500, null=True, verbose_name='paid_on'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='payment_filing_file',
            field=models.CharField(blank=True, help_text='payment_filing_file', max_length=500, null=True, verbose_name='payment_filing_file'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='payment_operation',
            field=models.CharField(blank=True, help_text='payment_operation', max_length=500, null=True, verbose_name='payment_operation'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='receipt_filing_file',
            field=models.CharField(blank=True, help_text='receipt_filing_file', max_length=500, null=True, verbose_name='receipt_filing_file'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='rfc',
            field=models.CharField(blank=True, help_text='rfc', max_length=500, null=True, verbose_name='rfc'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='taxes',
            field=models.CharField(blank=True, help_text='taxes', max_length=500, null=True, verbose_name='taxes'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='total_due',
            field=models.CharField(blank=True, help_text='total_due', max_length=500, null=True, verbose_name='total_due'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='total_paid_due',
            field=models.CharField(blank=True, help_text='total_paid_due', max_length=500, null=True, verbose_name='total_paid_due'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_declaracion',
            name='unknown_payment_status',
            field=models.CharField(blank=True, help_text='unknown_payment_status', max_length=500, null=True, verbose_name='unknown_payment_status'),
        ),
    ]
