# Generated by Django 3.1.1 on 2021-04-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listo_api', '0019_auto_20210423_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_factura',
            name='adjusted_subtotal_mxn',
            field=models.CharField(blank=True, help_text='adjusted_subtotal_mxn', max_length=1000, null=True, verbose_name='adjusted_subtotal_mxn'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='approval_num',
            field=models.CharField(blank=True, help_text='approval_num', max_length=1000, null=True, verbose_name='approval_num'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='approval_year',
            field=models.CharField(blank=True, help_text='approval_year', max_length=1000, null=True, verbose_name='approval_year'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='approved',
            field=models.CharField(blank=True, help_text='approved', max_length=1000, null=True, verbose_name='approved'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='approved_rejected_on',
            field=models.CharField(blank=True, help_text='approved_rejected_on', max_length=1000, null=True, verbose_name='approved_rejected_on'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='bank_account',
            field=models.CharField(blank=True, help_text='bank_account', max_length=1000, null=True, verbose_name='bank_account'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='canceled_on',
            field=models.CharField(blank=True, help_text='canceled_on', max_length=1000, null=True, verbose_name='canceled_on'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='cancellation_receipt_id',
            field=models.CharField(blank=True, help_text='cancellation_receipt_id', max_length=1000, null=True, verbose_name='cancellation_receipt_id'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='category_description',
            field=models.CharField(blank=True, help_text='category_description', max_length=1000, null=True, verbose_name='category_description'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='category_id',
            field=models.CharField(blank=True, help_text='category_id', max_length=1000, null=True, verbose_name='category_id'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='certificate',
            field=models.CharField(blank=True, help_text='certificate', max_length=1000, null=True, verbose_name='certificate'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='cfdi_signature',
            field=models.CharField(blank=True, help_text='cfdi_signature', max_length=1000, null=True, verbose_name='cfdi_signature'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='comments',
            field=models.CharField(blank=True, help_text='comments', max_length=1000, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='comments_approval_rejection',
            field=models.CharField(blank=True, help_text='comments_approval_rejection', max_length=1000, null=True, verbose_name='comments_approval_rejection'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='comments_for_supplier',
            field=models.CharField(blank=True, help_text='comments_for_supplier', max_length=1000, null=True, verbose_name='comments_for_supplier'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='counterparty_name',
            field=models.CharField(blank=True, help_text='counterparty_name', max_length=1000, null=True, verbose_name='counterparty_name'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='currency',
            field=models.CharField(blank=True, help_text='currency', max_length=1000, null=True, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='customer_id',
            field=models.CharField(blank=True, help_text='customer_id', max_length=1000, null=True, verbose_name='customer_id'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='customer_rfc_id',
            field=models.CharField(blank=True, help_text='customer_rfc_id', max_length=1000, null=True, verbose_name='customer_rfc_id'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='discounts',
            field=models.CharField(blank=True, help_text='discounts', max_length=1000, null=True, verbose_name='discounts'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='discounts_mxn',
            field=models.CharField(blank=True, help_text='discounts_mxn', max_length=1000, null=True, verbose_name='discounts_mxn'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='documents',
            field=models.CharField(blank=True, help_text='documents', max_length=1000, null=True, verbose_name='documents'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='due_on',
            field=models.CharField(blank=True, help_text='due_on', max_length=1000, null=True, verbose_name='due_on'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='email_status',
            field=models.CharField(blank=True, help_text='email_status', max_length=1000, null=True, verbose_name='email_status'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='extra_header_fields',
            field=models.CharField(blank=True, help_text='extra_header_fields', max_length=1000, null=True, verbose_name='extra_header_fields'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='folio',
            field=models.CharField(blank=True, help_text='folio', max_length=1000, null=True, verbose_name='folio'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='generated_invoice_id',
            field=models.CharField(blank=True, help_text='generated_invoice_id', max_length=1000, null=True, verbose_name='generated_invoice_id'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='goods_receipts',
            field=models.CharField(blank=True, help_text='goods_receipts', max_length=1000, null=True, verbose_name='goods_receipts'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='intended_use',
            field=models.CharField(blank=True, help_text='intended_use', max_length=1000, null=True, verbose_name='intended_use'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='intended_use_display',
            field=models.CharField(blank=True, help_text='intended_use_display', max_length=1000, null=True, verbose_name='intended_use_display'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='issued_at',
            field=models.CharField(blank=True, help_text='issued_at', max_length=1000, null=True, verbose_name='issued_at'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='issued_on',
            field=models.CharField(blank=True, help_text='issued_on', max_length=1000, null=True, verbose_name='issued_on'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='issued_on_display',
            field=models.CharField(blank=True, help_text='issued_on_display', max_length=1000, null=True, verbose_name='issued_on_display'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='issuer_address',
            field=models.CharField(blank=True, help_text='issuer_address', max_length=1000, null=True, verbose_name='issuer_address'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='issuer_name',
            field=models.CharField(blank=True, help_text='issuer_name', max_length=1000, null=True, verbose_name='issuer_name'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='issuer_regime',
            field=models.CharField(blank=True, help_text='issuer_regime', max_length=1000, null=True, verbose_name='issuer_regime'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='issuer_regime_display',
            field=models.CharField(blank=True, help_text='issuer_regime_display', max_length=1000, null=True, verbose_name='issuer_regime_display'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='issuer_rfc',
            field=models.CharField(blank=True, help_text='issuer_rfc', max_length=1000, null=True, verbose_name='issuer_rfc'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='modified_on',
            field=models.CharField(blank=True, help_text='modified_on', max_length=1000, null=True, verbose_name='modified_on'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='paid_on',
            field=models.CharField(blank=True, help_text='paid_on', max_length=1000, null=True, verbose_name='paid_on'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='payer_address',
            field=models.CharField(blank=True, help_text='payer_address', max_length=1000, null=True, verbose_name='payer_address'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='payer_name',
            field=models.CharField(blank=True, help_text='payer_name', max_length=1000, null=True, verbose_name='payer_name'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='payer_rfc',
            field=models.CharField(blank=True, help_text='payer_rfc', max_length=1000, null=True, verbose_name='payer_rfc'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='payment_acct_num',
            field=models.CharField(blank=True, help_text='payment_acct_num', max_length=1000, null=True, verbose_name='payment_acct_num'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='payment_form',
            field=models.CharField(blank=True, help_text='payment_form', max_length=1000, null=True, verbose_name='payment_form'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='payment_form_display',
            field=models.CharField(blank=True, help_text='payment_form_display', max_length=1000, null=True, verbose_name='payment_form_display'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='payment_method',
            field=models.CharField(blank=True, help_text='payment_method', max_length=1000, null=True, verbose_name='payment_method'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='payment_method_display',
            field=models.CharField(blank=True, help_text='payment_method_display', max_length=1000, null=True, verbose_name='payment_method_display'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='payment_state',
            field=models.CharField(blank=True, help_text='payment_state', max_length=1000, null=True, verbose_name='payment_state'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='payment_terms', max_length=1000, null=True, verbose_name='payment_terms'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='payments',
            field=models.CharField(blank=True, help_text='payments', max_length=1000, null=True, verbose_name='payments'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='payroll_data_display',
            field=models.CharField(blank=True, help_text='payroll_data_display', max_length=1000, null=True, verbose_name='payroll_data_display'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='purchase_orders',
            field=models.CharField(blank=True, help_text='purchase_orders', max_length=1000, null=True, verbose_name='purchase_orders'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='subtotal',
            field=models.CharField(blank=True, help_text='subtotal', max_length=1000, null=True, verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='subtotal_mxn',
            field=models.CharField(blank=True, help_text='subtotal_mxn', max_length=1000, null=True, verbose_name='subtotal_mxn'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='supplier_paid_on',
            field=models.CharField(blank=True, help_text='supplier_paid_on', max_length=1000, null=True, verbose_name='supplier_paid_on'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='tax_id',
            field=models.CharField(blank=True, help_text='tax_id', max_length=1000, null=True, verbose_name='tax_id'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='taxes_amount',
            field=models.CharField(blank=True, help_text='taxes_amount', max_length=1000, null=True, verbose_name='taxes_amount'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='taxes_amount_mxn',
            field=models.CharField(blank=True, help_text='taxes_amount_mxn', max_length=1000, null=True, verbose_name='taxes_amount_mxn'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='taxes_tax_rate',
            field=models.CharField(blank=True, help_text='taxes_tax_rate', max_length=1000, null=True, verbose_name='taxes_tax_rate'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='taxes_tax_type',
            field=models.CharField(blank=True, help_text='taxes_tax_type', max_length=1000, null=True, verbose_name='taxes_tax_type'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='taxes_treatment',
            field=models.CharField(blank=True, help_text='taxes_treatment', max_length=1000, null=True, verbose_name='taxes_treatment'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='total',
            field=models.CharField(blank=True, help_text='total', max_length=1000, null=True, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='total_mxn',
            field=models.CharField(blank=True, help_text='total_mxn', max_length=1000, null=True, verbose_name='total_mxn'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='total_paid',
            field=models.CharField(blank=True, help_text='total_paid', max_length=1000, null=True, verbose_name='total_paid'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='total_paid_mxn',
            field=models.CharField(blank=True, help_text='total_paid_mxn', max_length=1000, null=True, verbose_name='total_paid_mxn'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='total_supplier_paid',
            field=models.CharField(blank=True, help_text='total_supplier_paid', max_length=1000, null=True, verbose_name='total_supplier_paid'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='total_supplier_paid_mxn',
            field=models.CharField(blank=True, help_text='total_supplier_paid_mxn', max_length=1000, null=True, verbose_name='total_supplier_paid_mxn'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='uuid',
            field=models.CharField(blank=True, help_text='uuid', max_length=1000, null=True, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='validation_status_code',
            field=models.CharField(blank=True, help_text='validation_status_code', max_length=1000, null=True, verbose_name='validation_status_code'),
        ),
        migrations.AlterField(
            model_name='detalle_factura',
            name='validation_status_message',
            field=models.CharField(blank=True, help_text='validation_status_message', max_length=1000, null=True, verbose_name='validation_status_message'),
        ),
    ]
