# Generated by Django 3.1.1 on 2021-05-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listo_api', '0022_auto_20210503_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='adjusted_subtotal_mxn',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='payer_name',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='payer_rfc',
        ),
    ]
