# Generated by Django 3.1.1 on 2021-05-05 16:45

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listo_api', '0024_auto_20210505_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaraciones',
            name='json_filing',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='declaracionesdiots',
            name='json_filings_diots',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='detalle_declaracion_declaracion',
            name='json_filing_detail',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='diots',
            name='json_diot',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='lista69b',
            name='json_69b',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Detalle_Declaracion_Diots',
        ),
    ]
