# Generated by Django 3.1.1 on 2021-05-07 18:37

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listo_api', '0025_auto_20210505_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionlegal',
            name='json_direccion_legal',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='opinioncumplimiento',
            name='json_fulfillment_opinion',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
