# Generated by Django 3.1.1 on 2021-05-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listo_api', '0029_auto_20210511_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='adjusted_subtotal',
            field=models.CharField(blank=True, help_text='adjusted_subtotal', max_length=5000, null=True, verbose_name='adjusted_subtotal'),
        ),
        migrations.AddField(
            model_name='facturas',
            name='discounts',
            field=models.CharField(blank=True, help_text='discounts', max_length=5000, null=True, verbose_name='discounts'),
        ),
    ]
