# Generated by Django 3.1.1 on 2021-06-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listo_api', '0030_auto_20210512_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_declaracion_declaracion',
            name='filing_period_type',
            field=models.CharField(blank=True, help_text='filing_period_type', max_length=500, null=True, verbose_name='filing_period_type'),
        ),
    ]
