# Generated by Django 3.1.1 on 2021-06-04 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listo_api', '0031_detalle_declaracion_declaracion_filing_period_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_declaracion_declaracion',
            name='filing_period_period',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='filing_period_period', max_length=5000, null=True, verbose_name='filing_period_period'),
        ),
        migrations.AddField(
            model_name='detalle_declaracion_declaracion',
            name='filing_period_year',
            field=models.CharField(blank=True, help_text='filing_period_year', max_length=500, null=True, verbose_name='filing_period_year'),
        ),
    ]
