# Generated by Django 3.1.1 on 2021-07-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listo_api', '0032_auto_20210604_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionlegal',
            name='referencia',
            field=models.CharField(blank=True, help_text='referencia', max_length=1000, null=True, verbose_name='referencia'),
        ),
    ]
