# Generated by Django 3.0.8 on 2020-08-07 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCodeCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Código postal')),
                ('settlement', models.CharField(max_length=120, verbose_name='Colonia')),
                ('municipality', models.CharField(max_length=60, verbose_name='Municipio')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='Ciudad')),
                ('settlement_type', models.CharField(blank=True, max_length=30, verbose_name='Tipo de asentamiento')),
                ('estate', models.CharField(max_length=60, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Código postal',
                'verbose_name_plural': 'Códigos postales',
            },
        ),
    ]
