# Generated by Django 3.1 on 2020-08-31 04:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0002_auto_20200807_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='NirRulesCatalog',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text=('Indica si el registro debe ser tratado como activo.', 'Desmarque esta opción en lugar de borrar el registro'), verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Ultima modificación')),
                ('nir', models.IntegerField(primary_key=True, serialize=False, verbose_name='NIR')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs_nirrulescatalog_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs_nirrulescatalog_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
            ],
            options={
                'verbose_name': 'NIR',
                'verbose_name_plural': 'NIRS',
            },
        ),
        migrations.CreateModel(
            name='SeriesRulesCatalog',
            fields=[
                ('is_active', models.BooleanField(default=True, help_text=('Indica si el registro debe ser tratado como activo.', 'Desmarque esta opción en lugar de borrar el registro'), verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Ultima modificación')),
                ('nir_serie', models.IntegerField(primary_key=True, serialize=False, verbose_name='Nir_Serie')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs_seriesrulescatalog_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs_seriesrulescatalog_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
                ('nir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.nirrulescatalog', verbose_name='NIR')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='PhoneRulesCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text=('Indica si el registro debe ser tratado como activo.', 'Desmarque esta opción en lugar de borrar el registro'), verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Ultima modificación')),
                ('initial_number', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(0)], verbose_name='Numero inicial')),
                ('final_number', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(0)], verbose_name='Numero final')),
                ('kind_of_network', models.CharField(choices=[('FI', 'Telefono fijo'), ('MO', 'Telefono movil')], default='MO', max_length=2, verbose_name='Tipo de red')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs_phonerulescatalog_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs_phonerulescatalog_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
                ('nir_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.seriesrulescatalog', verbose_name='Nir_Serie')),
            ],
            options={
                'verbose_name': 'Rango',
                'verbose_name_plural': 'Rangos',
            },
        ),
    ]
