DROP TABLE IF EXISTS "api_listomx_declaraciones_periodo" CASCADE;
CREATE TABLE IF NOT EXISTS "api_listomx_declaraciones_periodo" (
"id" NUMERIC NOT NULL,
"rfc" NUMERIC NULL,
"period_type" TEXT NULL,
"period" TEXT NULL,
"year" NUMERIC NULL,
"total_paid_due" DECIMAL NULL,
"filing_due_on" TIMESTAMP NULL,
"diot_due_on" TIMESTAMP NULL,
"payment_status" TEXT NULL,
"period_description" TEXT NULL,
"period_type_description" TEXT NULL,
"general_status" TEXT NULL,
"diot_general_status" TEXT NULL,
"days_to_pay" TEXT NULL,
"days_to_file" NUMERIC NULL,
"to_be_paid_due" DECIMAL NULL,
"compensable_due" DECIMAL NULL,
"payable_due" DECIMAL NULL,
"checksum" DECIMAL NULL,
"nearest_payment_on" TIMESTAMP NULL,
"last_payment_on" TIMESTAMP NULL,
"last_filing_filed_on" TIMESTAMP NULL,
"days_to_file_diot" NUMERIC NULL,
"last_diot_filed_on" TIMESTAMP NULL,
"expired_taxes" JSON NULL,
"has_unkown_payment_status" BOOL NULL,
"period_only_description" TEXT NULL,
"period_short_description" TEXT NULL,
"creditable_due" DECIMAL NULL,
"taxes" JSON NULL,
"capture_line_expire_on" TIMESTAMP NULL,
"has_complementary_filings" BOOL NULL,
"electronic_accounting_filings" JSON NULL,
PRIMARY KEY(id),
FOREIGN KEY(rfc) REFERENCES api_listomx_rfc(id)
)