DROP TABLE IF EXISTS "api_listomx_declaraciones_declaracion" CASCADE;

CREATE TABLE IF NOT EXISTS "api_listomx_declaraciones_declaracion" (
"id" NUMERIC NULL,
"days_to_pay" TEXT NULL,
"payment_status" TEXT NULL,
"general_status" TEXT NULL,
"checksum" DECIMAL NULL,
"creditable_due" DECIMAL NULL,
"compensable_due" DECIMAL NULL,
"capture_line_expire_on" TIMESTAMP NULL,
"expired_taxes" TEXT NULL,
"rfc" TEXT NULL,
"filed_filing_file" NUMERIC NULL,
"paid_filing_file" NUMERIC NULL,
"receipt_filing_file" NUMERIC NULL,
"payment_filing_file" TEXT NULL,
"filed_filing_doc" NUMERIC NULL,
"receipt_filing_doc" NUMERIC NULL,
"model_version" NUMERIC NULL,
"operation_number" NUMERIC NULL,
"filed_on" TIMESTAMP NULL,
"filed_timestamp" TEXT NULL,
"filing_type" TEXT NULL,
"complimentary_type" TEXT NULL,
"capture_line" TEXT NULL,
"total_due" DECIMAL NULL,
"total_paid_due" DECIMAL NULL,
"is_paid" BOOL NULL,
"bank" TEXT NULL,
"payment_operation" TEXT NULL,
"paid_on" TIMESTAMP NULL,
"unknown_payment_status" BOOL NULL,
"created_on" TIMESTAMP NULL,
"filing_period" NUMERIC NULL,
"paid_filing_doc" NUMERIC NULL,
"financial_statement" JSON NULL,
PRIMARY KEY(id),
FOREIGN KEY(filing_period) REFERENCES api_listomx_declaraciones_periodo(id)
);