DROP TABLE IF EXISTS "api_listomx_declaraciones_impuesto" CASCADE;
CREATE TABLE IF NOT EXISTS "api_listomx_declaraciones_impuesto" (
"id" NUMERIC NULL,
"payable_due" DECIMAL NULL,
"compensable_due" DECIMAL NULL,
"real_total_paid_due" DECIMAL NULL,
"real_previously_paid_due" DECIMAL NULL,
"to_be_paid_or_compensable_due" DECIMAL NULL,
"checksum" DECIMAL NULL,
"filing_number" NUMERIC NULL,
"model_version" NUMERIC NULL,
"tax_type" TEXT NULL,
"current" BOOL NULL,
"due" DECIMAL NULL,
"contibution_due" DECIMAL NULL,
"previously_paid_due" DECIMAL NULL,
"charge_due" DECIMAL NULL,
"actualized_due" DECIMAL NULL,
"recharged_due" DECIMAL NULL,
"fine_due" DECIMAL NULL,
"compensation_due" DECIMAL NULL,
"application_due" DECIMAL NULL,
"iva_due" DECIMAL NULL,
"iva_recoverable_due" DECIMAL NULL,
"iva_charge_due" DECIMAL NULL,
"iva_withheld_due" DECIMAL NULL,
"iva_accreditation_due" DECIMAL NULL,
"isr_income_due" DECIMAL NULL,
"isr_expense_due" DECIMAL NULL,
"isr_prev_paid_due" DECIMAL NULL,
"isr_withheld_due" DECIMAL NULL,
"isr_due" DECIMAL NULL,
"rfc" NUMERIC NULL,
"filing_period" NUMERIC NULL,
"filing" NUMERIC NULL,
PRIMARY KEY(id),
FOREIGN KEY(rfc) REFERENCES api_listomx_rfc(id),
FOREIGN KEY(filing_period) REFERENCES api_listomx_declaraciones_periodo(id),
FOREIGN KEY(filing) REFERENCES api_listomx_declaraciones_declaracion(id)
);