# Generated by Django 3.0.8 on 2020-08-08 01:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_auto_20200807_1714'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='external_num',
            field=models.CharField(default='', help_text='Número o letras exterior', max_length=10, verbose_name='Número externo'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='internal_num',
            field=models.CharField(default='', help_text='Número o letras interior', max_length=10, verbose_name='Número interno'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ciec',
            field=models.CharField(blank=True, help_text='Contrasñea SAT', max_length=32, null=True, verbose_name='CIEC'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street',
            field=models.CharField(default='', help_text='Nombre de la calle', max_length=255, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(13)], verbose_name='RFC'),
        ),
        migrations.CreateModel(
            name='ContactUserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text=('Indica si el registro debe ser tratado como activo.', 'Desmarque esta opción en lugar de borrar el registro'), verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Ultima modificación')),
                ('street', models.CharField(default='', help_text='Nombre de la calle', max_length=255, verbose_name='Calle')),
                ('external_num', models.CharField(default='', help_text='Número o letras exterior', max_length=10, verbose_name='Número externo')),
                ('internal_num', models.CharField(default='', help_text='Número o letras interior', max_length=10, verbose_name='Número interno')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_contactuseraddress_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_contactuseraddress_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
                ('postal_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.PostalCodeCatalog', verbose_name='Código postal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.ContactUser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dirección del contacto',
                'verbose_name_plural': 'Direcciones de contactos',
                'ordering': ('id',),
            },
        ),
    ]
