# Generated by Django 3.0.8 on 2020-08-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200807_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='authority_doc',
            field=models.FileField(blank=True, max_length=300, upload_to='users/documents/authority_doc/%Y/%m/%d/', verbose_name='Poderes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='constitutive_act',
            field=models.FileField(blank=True, max_length=300, upload_to='users/documents/constitutive_act/%Y/%m/%d/', verbose_name='Acta constitutiva'),
        ),
    ]
