# Generated by Django 3.0.8 on 2020-08-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200807_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileRole',
            fields=[
                ('role', models.CharField(max_length=24, primary_key=True, serialize=False, unique=True, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Ultima modificación')),
            ],
            options={
                'verbose_name': 'Rol de usuario',
                'verbose_name_plural': 'Roles de usuarios',
            },
        ),
    ]
