# Generated by Django 3.0.8 on 2020-08-08 12:45

from django.db import migrations


def create_default_user_profile_roles(apps, schema_editor):
    UserProfileRole = apps.get_model('users', 'UserProfileRole')

    UserProfileRole.objects.create(role='admin')
    UserProfileRole.objects.create(role='manager')
    UserProfileRole.objects.create(role='client')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofilerole'),
    ]

    operations = [
        migrations.RunPython(create_default_user_profile_roles),
    ]
