# Generated by Django 3.0.8 on 2020-08-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(default='client', on_delete=django.db.models.deletion.CASCADE, to='users.UserProfileRole', verbose_name='Rol de usuario'),
        ),
    ]
