# Generated by Django 3.0.8 on 2020-08-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='official_identification',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='official_identification_back',
            field=models.FileField(blank=True, max_length=300, upload_to='users/documents/official_identification_back/%Y/%m/%d/', verbose_name='Identificación oficial'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='official_identification_front',
            field=models.FileField(blank=True, max_length=300, upload_to='users/documents/official_identification_front/%Y/%m/%d/', verbose_name='Identificación oficial'),
        ),
    ]
