# Generated by Django 3.0.8 on 2020-08-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usertemporalmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemporalmedia',
            name='validation_video',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='users/documents/validation_video/%Y/%m/%d/', verbose_name='Video de validacion'),
        ),
    ]
