# Generated by Django 3.1.2 on 2020-12-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usertemporalmedia_curp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latitud',
            field=models.CharField(blank=True, help_text='Latitud', max_length=16, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitud',
            field=models.CharField(blank=True, help_text='Longitud', max_length=16, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text=('Indica si el registro debe ser tratado como activo.', 'Desmarque esta opción en lugar de borrar el registro'), verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Set to true when the user have verified its email address.', verbose_name='verified'),
        ),
    ]
