# Generated by Django 3.1.2 on 2020-12-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201223_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='num_crp_issued',
            field=models.IntegerField(blank=True, help_text='num_crp_issued', null=True, verbose_name='num_crp_issued'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='num_crp_received',
            field=models.IntegerField(blank=True, help_text='num_crp_received', null=True, verbose_name='num_crp_received'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='num_payroll_issued',
            field=models.IntegerField(blank=True, help_text='num_payroll_issued', null=True, verbose_name='num_payroll_issued'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='num_payroll_received',
            field=models.IntegerField(blank=True, help_text='num_payroll_received', null=True, verbose_name='num_payroll_received'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='num_regular_issued',
            field=models.IntegerField(blank=True, help_text='num_regular_issued', null=True, verbose_name='num_regular_issued'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='num_regular_received',
            field=models.IntegerField(blank=True, help_text='num_regular_received', null=True, verbose_name='num_regular_received'),
        ),
    ]
