# Generated by Django 3.1.2 on 2020-12-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201224_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_sended',
            field=models.BooleanField(default=False, help_text='Indica si el contrato a firmar ya fue enviado', verbose_name='contrato_enviado'),
        ),
        migrations.AddField(
            model_name='user',
            name='contract_signed',
            field=models.BooleanField(default=False, help_text='Indica si el contrato ya fue firmado', verbose_name='contrato_firmado'),
        ),
    ]
