# Generated by Django 3.1.2 on 2020-12-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201224_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aprovado',
            field=models.BooleanField(default=False, help_text='Indica si el usuario es aprovado', verbose_name='aprovado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ip_client',
            field=models.IntegerField(blank=True, help_text='ip de cliente', null=True, verbose_name='ip_client'),
        ),
    ]
