# Generated by Django 3.1.2 on 2020-12-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201229_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ip_client',
            field=models.CharField(blank=True, help_text='ip de cliente', max_length=16, null=True, verbose_name='ip_client'),
        ),
    ]
