# Generated by Django 3.1.2 on 2021-01-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201229_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_listo',
            field=models.CharField(blank=True, help_text='token de listo', max_length=100, null=True, verbose_name='token_listo'),
        ),
    ]
