# Generated by Django 3.1.2 on 2021-01-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_token_listo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rfc_id',
            field=models.IntegerField(blank=True, help_text='rfc_id', null=True, verbose_name='rfc_id'),
        ),
    ]
