# Generated by Django 3.1.2 on 2021-01-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userprofile_rfc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token_listo',
            field=models.CharField(blank=True, help_text='token de listo', max_length=100, null=True, verbose_name='token_listo'),
        ),
    ]
