# Generated by Django 3.1.2 on 2021-01-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_url_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='url_documento',
            field=models.CharField(blank=True, help_text='url documento de firmamex', max_length=100, null=True, verbose_name='url_documento'),
        ),
    ]
