# Generated by Django 3.1.1 on 2021-01-27 00:49

from django.db import migrations
from django.core.management import call_command
import os
from sys import path

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
fixture_filename = 'catalogs.postalcode.json'

def load_fixture(apps, schema_editor):
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    call_command('loaddata', fixture_file)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_userprofile_ticket_documento'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
