# Generated by Django 3.1.1 on 2021-01-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_migration_codpos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ip_client',
            field=models.CharField(blank=True, help_text='ip de cliente', max_length=100, null=True, verbose_name='ip_client'),
        ),
    ]
